server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


spring:
  application:
    name: cloud-consumer-hystrix-order

#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true  # 如果处理自身的容 错 就 开启 。 开启 方式 与 生 产 端不一 样 。